apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ack-system

bases:
  - ../../ack-s3-controller/operator/overlays/default
  - ../../ack-sagemaker-controller/operator/overlays/default
