---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: AWS Operators
  name: ack-system
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ack-operatorgroup
  namespace: ack-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ack-sagemaker-controller.ack-system: ""
  name: ack-sagemaker-controller
  namespace: ack-system
spec:
  channel: patch-me
  installPlanApproval: Automatic
  name: ack-sagemaker-controller
  source: community-operators
  sourceNamespace: openshift-marketplace
