apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-client-secret
  namespace: default
spec:
  encryptedData:
    clientSecret: AgAq2FeZ5708YRGcOvVZrny22bMdpthCFErWUSxIIh/K/DurSkyjwrDQuUpvb7tRzvYahdUWM9FVlCFWEIUu7/XV9dGuzVLZzdyqadK1QdGITC2JLINSzQC6eLNDvpIl3hl/yiSEYpZfCGX/Nqh0oerrawzRUl9TQl6PW1XHBU8VBEtOewlYhaq4YEIreI3xDvZkWpOygAmK5K1yLEROxPxSFy5d5QUMAXGRSOkH6lLcLiCNa9XAI1z8LD53CAR2Y6Z7EqvucilyTyDkzvny5Z2gyWqJSYMjVL28/K8znhgz1bbKVxYlyNj8/oLbM68Vk3Rd03TxrE5AC5MibIb2B9kwVjt1jpkWbOEEnoOLyv19ZIEUcfLruXj+eRGrLb04t4Hwn2+GerxWjVeWeEe0qVtG/UzKP7JBmLGvxkTSBeG0EuwZFvRrL4WJnt6Ual1FV5v2BmporOqKsbleAgR8Bq7l4vdN/mBtrMhORjQbBuo4P8XSnfA0m5nqawBqltOR+g+6tDOAD3sKvEW0YdJRvZ+aDpJeHPJSCvnCQ+vqBz3cTnEhAHt0q4fek4qpk2S7cIEIOTGcFaW7NprVlkomNb4fF5GcVyKJU2N2nHHnno1FQowWa0TBLw755Cvhlt6o8Ma5nqqyOFmPCLXiawqxgU6igyo4G8LXSItmUC1YAURyyigLJKpQdfWX2wwjqKX+uO051BElufG1W/5Xvw/3R7K2eowVOBaQ31gbKu/VWbFD59msmwo7eWYt
  template:
    metadata:
      name: github-client-secret
      namespace: openshift-config
