apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - cluster-admins-group.yaml
  - cluster-admins-rolebinding.yaml
  - cluster-readers-group.yaml
  - cluster-readers-rolebinding.yaml
  - workshop-admins-group.yaml

patchesJson6902:
  - target:
      group: machineconfiguration.openshift.io
      version: v1
      kind: MachineConfig
      name: 99-master-ssh
    path: patch-ssh.yaml
  - target:
      group: machineconfiguration.openshift.io
      version: v1
      kind: MachineConfig
      name: 99-worker-ssh
    path: patch-ssh.yaml