apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-ack-system
  namespace: openshift-gitops
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/operators/aws-controllers/overlays/default
    repoURL: git@github.com:redhat-na-ssa/ds-tiger-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
