- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-keda
        path: components/operators/openshift-keda/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-web-terminal
        path: components/operators/web-terminal-operator/operator/overlays/fast
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-tekton
        path: components/operators/openshift-pipelines-operator/overlays/stable
