apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ack-sagemaker-user-secrets
  namespace: ack-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBSnuv8QHszKsVeDBCvtyha4lOYgAunxFDAOsKKg2mI/h7YTLS23rpeZsHnvylWbHip25D7o6ogAya+6e4Nu/Gm5msjlCXUs4g9tEAJ+UrB0OpxuaqlklkXPHh7BSmarfHjfqlkQ5oAjVE5a13KPcMRmpsVyv7XdVl30w7Hray4+hjSV93eEZjrBZbOKMyjf8g0KGDGzVzW9rp5kPMzu2XPVc2vIw2xnrs4KI88A8xUd9kvcmKGtKyGyHm5XKAitJM5Wrbdt4Wx9lSl4vDJZPRiBYDjiOlS69jw3174/79PcAKbHCmsh/staZtZg4FxTP9fgYAIrJgLVhTJrFcqkf+FJgp/7/vYu2284R59+46mec7YzsaEyJLCTOOWUlq/+pSyl7TkdY0SwAl6rU4AWvRi7uMLWAcnib3WnYwG9vtXUG49aRwYGmJAEpnsyMTBcRpFUOdJjMtV9y+iw+IRnd972Jpr/e90afBgn9I6n2Kigqyr45IuN5yBLWuOMp8SDGyCLa/TFHV+xtVeMNObLL3CZJP4+9Xls5nHuYll0gTfMLviuDSDwPvttM9ZIj9J4UxYzAclR1Et0WhMzzs5Wt0TQJ0ykxGVek5xp/3JxEdMdWOP29lDXc527YWrZ4/25Cy7z8LrJz4t4pJgle/bXVWBFEayCzvN9F3znWn0+pG56hP9RPgcJJUqhXxkc01PYsbCJAHQDbWBLgqlu0PsblpMHazO5A==
    AWS_SECRET_ACCESS_KEY: AgCtoD2778rugszaB5VlQ84WATBFhcziqJ4s3jbd+OEWsi40Rdm5Ozfe/vKEYxHjr+6+GZrREAdXdHnZqq2m0TbfPht+87xD+VxoP6zmF2fYC8n+IsiPT16LaAyD9iL6KWg91zepJwXGynPXC6BqzNF0daKjuowx549S6572sJ4Pk32S10Rhn2YsjriENa3pUqIrNfYZzNqbqVukxdDNkmUT+1yBiBA5fwQiNi9Hkr999ngHX4GqXTxZO4YcwBnetkt2ciOQblTTbSYYmSDOSmf5/qc5LyAs6QafCill6AB9z6w1vd2ImqyhdxEeAOY9YL2jXQ3ZPUhgXfzr36kc3K/COt2YWNG76s/t2UWzpE/+r/f0HV8v0E3pmbLgeyR0sJG4/BdKl9z5tLyiO5zUdxoY1/hIHXokO0A97AyW5wz8pvtaMbREMv/n6MMmfuaFhUbnNEv4BVqazBXbfxuGG6h9V7Xf/CS4pVpvLnXG1S0akWCJJl4CpeHaaQmY66NZLgzfUDWafdkJyAJWQoGkqie2D7SBSct2ZUWCFpOK+eF2KB6g9ME2KfIKgfwKPwkllO4KdaaaVT+byYB+6eZ5mhPV3AEo8EXiIkkKoh0MRhjdzIFTwg9Y9Er8/xUNfkk+CoTJ4lwv5KtD9qXjCVWKNcc8mU6NrvhEkx2/Q4mh5QnTEL5FqZ4FpkO1AvT9T69X33Ntaw0kt4lmXiBi4yeAm+VYHqdTpoRQCvaAYfpmTis4SYFbJb1hKK2m
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: ack-sagemaker-user-secrets
      namespace: ack-system
