---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../alpha

patches:
  - target:
      kind: Subscription
      name: ack-s3-controller
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'alpha'

resources:
  - user-secrets-ss.yaml
