- op: add
  # path: /spec/identityProviders/-
  path: /spec/identityProviders
  value:
    - github:
        clientID: d7944d70f41af73c99d8
        clientSecret:
          name: github-client-secret
        organizations:
          - redhat-manufacturing
          - redhat-na-ssa
      mappingMethod: claim
      name: GitHub
      type: GitHub
