apiVersion: v1
kind: LimitRange
metadata:
  name: sandbox-limit-range
  namespace: sandbox
spec:
  limits:
    - type: Container
      default:
        memory: 1Gi
        cpu: 800m
      defaultRequest:
        memory: 256Mi
        cpu: 200m
      # max:
      #   cpu: '4'
      #   memory: 8Gi
